# -*- coding: utf-8 -*-
"""wine_quality_1 (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1duLY3i4Xe_N0Kck2nfTpqXmckjx_6L1t

# Naive bayes classifier algorithm¶
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
df=pd.read_csv(r"final_alcohol.csv")
df

df.head(2)

df.shape

df.info()

df.describe()

df.isnull().sum().sum()

print(df['quality'].value_counts())

df.columns

df.Type.unique()

def clean_data(st):
    st=st.strip()
    return st

clean_data('White Wine')

df.Type=df.Type.apply(clean_data)

df.Type.unique()

df['Type']=df['Type'].replace(['White Wine', 'Red Wine'],[1,0])
df

input_data=df.drop(columns=['quality'])
output_data=df['quality']

input_data

output_data

sns.boxplot(df['alcohol'],orient='h')

sns.catplot(x="quality", data=df,kind="count")
plt.show()

x=df.iloc[:,0:-1].values
y=df.iloc[:,-1].values

print("shape of x:",x.shape)
print("shape of y:",y.shape)

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y, test_size=0.30, random_state=20)

print("print x_train:",x_train.shape)
print("print x_test:",x_test.shape)

print("print y_train:",y_train.shape)
print("print y_test:",y_test.shape)

"""# Gaussian"""

from sklearn.naive_bayes import GaussianNB
classifier=GaussianNB()
classifier.fit(x_train,y_train)

classifier.score(x_test,y_test)

"""# Multinominal"""

from sklearn.naive_bayes import MultinomialNB
cm=MultinomialNB()
cm.fit(x_train,y_train)

cm.score(x_test,y_test)

"""# Bernoulli"""

from sklearn.naive_bayes import BernoulliNB
cb=BernoulliNB()
cb.fit(x_train,y_train)

cb.score(x_test,y_test)

"""# Confusion matrix"""

y_pred=classifier.predict(x_test)

import seaborn as sns
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)

sns.heatmap (cm,annot=True,fmt='g')

# correlation
df=df.select_dtypes(include=['int64','float64'])

plt.figure(figsize=(15,15))
sns.heatmap(df.corr(),annot=True,cmap='coolwarm')
plt.show()

from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score

cm=confusion_matrix(y_test,y_pred)

accuracy=accuracy_score(y_test,y_pred)
print("Accuracy:", accuracy)

pre=precision_score(y_test,y_pred)
print("Precision:", pre)

re=recall_score(y_test,y_pred)
print("Recall:",re)

f1=f1_score(y_test,y_pred)
print("F1:",f1)

metrics = ['Accuracy', 'Precision', 'Recall', 'F1 Score']
values = [accuracy, pre, re, f1]
plt.bar(metrics, values, color=['blue','green','orange','red'])

plt.ylim(0,1)
plt.title("Model Performance")
plt.ylabel("Score")

plt.show()

